ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi
ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
