ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi
ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += lm3646.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
