ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi
ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_xiaomi/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
